{% set name = "randonneur_data" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 991e90009b9ede4a54770a4658dee36065eb03032a42cfeea0ac7d11dfad37c0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-build-isolation --no-deps . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=68.0
  run:
    - python >={{ python_min }}

test:
  imports:
    - randonneur_data
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/brightway-lca/randonneur_data
  summary: 'Data for the randonneur ETL library and spec'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/brightway-lca/randonneur_data

extra:
  recipe-maintainers:
    - m-rossi
